import { Product } from "@/types/product";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod_01",
    name: "Imperial Opera Luxury Perfume",
    slug: "imperial-opera",
    category: "Fragrance",
    description: "A signature luxury perfume blending rich oriental notes with modern elegance. Perfect for evening wear.",
    images: [
      "/assets/imperial-opera/Imperial-Opera-Luxury-Perfume-1.webp",
      "/assets/imperial-opera/Imperial-Opera-Luxury-Perfume-2.png",
      "/assets/imperial-opera/Imperial-Opera-Luxury-Perfume-3.jpeg"
    ],
    frames360: [],
    wholesaleTier: { moq: 100, pricePerUnit: 1200 },
    retailerTier: { moq: 6, pricePerUnit: 1800 },
    consumerTier: { moq: 1, pricePerUnit: 2499 },
    nasioUrl: "https://nas.io/acinnovationsandventures/physical-products/imperial-opera-luxury-perfume",
    marketPrice: 1500,
    retailStorePrice: 3200,
    inStock: true,
    tags: ["perfume", "luxury", "fragrance", "imperial"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "prod_02",
    name: "OVI Desert Caravan Pocket Perfume",
    slug: "desert-caravan",
    category: "Fragrance",
    description: "Compact and travel-friendly pocket perfume with long-lasting desert woody notes.",
    images: [
      "/assets/desert-caravan/Desert-Caravan-Pocket-Perfume-1.webp",
      "/assets/desert-caravan/Desert-Caravan-Pocket-Perfume-2.webp",
      "/assets/desert-caravan/Desert-Caravan-Pocket-Perfume-3.webp"
    ],
    frames360: [],
    wholesaleTier: { moq: 100, pricePerUnit: 150 },
    retailerTier: { moq: 6, pricePerUnit: 250 },
    consumerTier: { moq: 1, pricePerUnit: 399 },
    nasioUrl: "https://nas.io/acinnovationsandventures/physical-products/ovi-desert-caravan-pocket-perfume",
    marketPrice: 200,
    retailStorePrice: 499,
    inStock: true,
    tags: ["pocket", "travel", "perfume", "fragrance"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "prod_03",
    name: "CVI Maharaja's Court Luxury Perfume",
    slug: "maharajas-court",
    category: "Fragrance",
    description: "Experience the royal essence with Mahajara's Court. Inspired by traditional Indian royalty with deep amber and sandalwood.",
    images: [
      "/assets/maharajas-court/Maharaja’s-Court-Luxury-Perfume-1.webp",
      "/assets/maharajas-court/Maharaja’s-Court-Luxury-Perfume-2.jpeg",
      "/assets/maharajas-court/Maharaja’s-Court-Luxury-Perfume-3.webp"
    ],
    frames360: [],
    wholesaleTier: { moq: 100, pricePerUnit: 1350 },
    retailerTier: { moq: 6, pricePerUnit: 1900 },
    consumerTier: { moq: 1, pricePerUnit: 2799 },
    nasioUrl: "https://nas.io/acinnovationsandventures/physical-products/cvi-maharajas-court-luxury-perfume",
    marketPrice: 1600,
    retailStorePrice: 3500,
    inStock: true,
    tags: ["perfume", "royal", "maharaja", "luxury"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },



  {
    id: "prod_05",
    name: "Nike Air Jordan 1 Red And Black",
    slug: "nike-air-jordan-1-red-and-black",
    category: "Sneakers",
    description: "The Nike Air Jordan 1 in Red and Black is an iconic basketball sneaker known for its stylish design and high-performance features, making it a favorite among sneaker enthusiasts and athletes.",
    images: [
      "https://cdn.dummyjson.com/product-images/mens-shoes/nike-air-jordan-1-red-and-black/1.webp",
      "https://cdn.dummyjson.com/product-images/mens-shoes/nike-air-jordan-1-red-and-black/2.webp",
      "https://cdn.dummyjson.com/product-images/mens-shoes/nike-air-jordan-1-red-and-black/3.webp",
      "https://cdn.dummyjson.com/product-images/mens-shoes/nike-air-jordan-1-red-and-black/4.webp"
    ],
    frames360: [],
    wholesaleTier: { moq: 50, pricePerUnit: 5500 },
    retailerTier: { moq: 10, pricePerUnit: 8500 },
    consumerTier: { moq: 1, pricePerUnit: 12499 },
    nasioUrl: "https://nas.io/acinnovationsandventures/physical-products/nike-air-jordan-1-red-and-black",
    marketPrice: 7000,
    retailStorePrice: 14999,
    inStock: true,
    tags: ["sneakers", "nike", "jordan", "shoes"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "prod_06",
    name: "Nike Baseball Cleats",
    slug: "nike-baseball-cleats",
    category: "Sneakers",
    description: "Nike Baseball Cleats are designed for maximum traction and performance on the field. They provide stability and support for players during games and practices.",
    images: [
      "https://cdn.dummyjson.com/product-images/mens-shoes/nike-baseball-cleats/1.webp",
      "https://cdn.dummyjson.com/product-images/mens-shoes/nike-baseball-cleats/2.webp",
      "https://cdn.dummyjson.com/product-images/mens-shoes/nike-baseball-cleats/3.webp",
      "https://cdn.dummyjson.com/product-images/mens-shoes/nike-baseball-cleats/4.webp"
    ],
    frames360: [],
    wholesaleTier: { moq: 50, pricePerUnit: 3200 },
    retailerTier: { moq: 10, pricePerUnit: 4800 },
    consumerTier: { moq: 1, pricePerUnit: 6999 },
    nasioUrl: "https://nas.io/acinnovationsandventures/physical-products/nike-baseball-cleats",
    marketPrice: 4000,
    retailStorePrice: 7999,
    inStock: true,
    tags: ["sneakers", "nike", "cleats", "sports"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "prod_07",
    name: "iPhone 5s",
    slug: "iphone-5s",
    category: "Mobile",
    description: "The iPhone 5s is a classic smartphone known for its compact design and advanced features. While it's an older model, it still provides a reliable user experience for basic use.",
    images: [
      "https://cdn.dummyjson.com/product-images/smartphones/iphone-5s/1.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/iphone-5s/2.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/iphone-5s/3.webp"
    ],
    frames360: [],
    wholesaleTier: { moq: 50, pricePerUnit: 3500 },
    retailerTier: { moq: 10, pricePerUnit: 5500 },
    consumerTier: { moq: 1, pricePerUnit: 7999 },
    nasioUrl: "https://nas.io/acinnovationsandventures/physical-products/iphone-5s",
    marketPrice: 4500,
    retailStorePrice: 8999,
    inStock: true,
    tags: ["mobile", "iphone", "apple", "smartphone"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "prod_08",
    name: "iPhone 6",
    slug: "iphone-6",
    category: "Mobile",
    description: "The iPhone 6 is a stylish and capable smartphone with a larger display and improved performance. It introduced new features and design elements, making it a popular choice in its time.",
    images: [
      "https://cdn.dummyjson.com/product-images/smartphones/iphone-6/1.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/iphone-6/2.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/iphone-6/3.webp"
    ],
    frames360: [],
    wholesaleTier: { moq: 50, pricePerUnit: 5000 },
    retailerTier: { moq: 10, pricePerUnit: 7500 },
    consumerTier: { moq: 1, pricePerUnit: 10999 },
    nasioUrl: "https://nas.io/acinnovationsandventures/physical-products/iphone-6",
    marketPrice: 6500,
    retailStorePrice: 12999,
    inStock: true,
    tags: ["mobile", "iphone", "apple", "smartphone"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "prod_09",
    name: "Apple MacBook Pro 14 Inch Space Grey",
    slug: "apple-macbook-pro-14-inch-space-grey",
    category: "Electronics",
    description: "The MacBook Pro 14 Inch in Space Grey is a powerful and sleek laptop, featuring Apple's M1 Pro chip for exceptional performance and a stunning Retina display.",
    images: [
      "https://cdn.dummyjson.com/product-images/laptops/apple-macbook-pro-14-inch-space-grey/1.webp",
      "https://cdn.dummyjson.com/product-images/laptops/apple-macbook-pro-14-inch-space-grey/2.webp",
      "https://cdn.dummyjson.com/product-images/laptops/apple-macbook-pro-14-inch-space-grey/3.webp"
    ],
    frames360: [],
    wholesaleTier: { moq: 20, pricePerUnit: 125000 },
    retailerTier: { moq: 5, pricePerUnit: 165000 },
    consumerTier: { moq: 1, pricePerUnit: 199999 },
    nasioUrl: "https://nas.io/acinnovationsandventures/physical-products/apple-macbook-pro-14-inch-space-grey",
    marketPrice: 145000,
    retailStorePrice: 219999,
    inStock: true,
    tags: ["electronics", "laptop", "apple", "macbook"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "prod_10",
    name: "Asus Zenbook Pro Dual Screen Laptop",
    slug: "asus-zenbook-pro-dual-screen-laptop",
    category: "Electronics",
    description: "The Asus Zenbook Pro Dual Screen Laptop is a high-performance device with dual screens, providing productivity and versatility for creative professionals.",
    images: [
      "https://cdn.dummyjson.com/product-images/laptops/asus-zenbook-pro-dual-screen-laptop/1.webp",
      "https://cdn.dummyjson.com/product-images/laptops/asus-zenbook-pro-dual-screen-laptop/2.webp",
      "https://cdn.dummyjson.com/product-images/laptops/asus-zenbook-pro-dual-screen-laptop/3.webp"
    ],
    frames360: [],
    wholesaleTier: { moq: 20, pricePerUnit: 95000 },
    retailerTier: { moq: 5, pricePerUnit: 130000 },
    consumerTier: { moq: 1, pricePerUnit: 159999 },
    nasioUrl: "https://nas.io/acinnovationsandventures/physical-products/asus-zenbook-pro-dual-screen-laptop",
    marketPrice: 110000,
    retailStorePrice: 179999,
    inStock: true,
    tags: ["electronics", "laptop", "asus", "dual-screen"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "prod_11",
    name: "Samsung 55\" Crystal 4K UHD Smart TV",
    slug: "samsung-55-crystal-4k-uhd-smart-tv",
    category: "TV",
    description: "Experience stunning 4K resolution with Samsung's Crystal UHD Smart TV. Features HDR support, built-in voice assistants, and a sleek slim design perfect for any living space.",
    images: [
      "https://cdn.dummyjson.com/product-images/home-decoration/family-tree-photo-frame/1.webp"
    ],
    frames360: [],
    wholesaleTier: { moq: 20, pricePerUnit: 25000 },
    retailerTier: { moq: 5, pricePerUnit: 35000 },
    consumerTier: { moq: 1, pricePerUnit: 44999 },
    nasioUrl: "https://nas.io/acinnovationsandventures/physical-products/samsung-55-crystal-4k-uhd-smart-tv",
    marketPrice: 30000,
    retailStorePrice: 49999,
    inStock: true,
    tags: ["tv", "samsung", "4k", "smart-tv"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "prod_12",
    name: "RC Racing Car with Remote Control",
    slug: "rc-racing-car-remote-control",
    category: "Toys",
    description: "High-speed remote control racing car with rechargeable battery, LED lights, and durable shock-proof body. Perfect for kids aged 6+ and hobby enthusiasts.",
    images: [
      "https://cdn.dummyjson.com/product-images/motorcycle/generic-motorcycle/1.webp",
      "https://cdn.dummyjson.com/product-images/motorcycle/generic-motorcycle/2.webp"
    ],
    frames360: [],
    wholesaleTier: { moq: 100, pricePerUnit: 450 },
    retailerTier: { moq: 20, pricePerUnit: 750 },
    consumerTier: { moq: 1, pricePerUnit: 1299 },
    nasioUrl: "https://nas.io/acinnovationsandventures/physical-products/rc-racing-car-remote-control",
    marketPrice: 600,
    retailStorePrice: 1499,
    inStock: true,
    tags: ["toys", "rc-car", "remote-control", "kids"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "prod_13",
    name: "Decoration Swing Toy Set",
    slug: "decoration-swing-toy-set",
    category: "Toys",
    description: "The Decoration Swing Toy Set is a charming miniature playset with detailed craftsmanship. A perfect collectible or decorative piece for kids and adults alike.",
    images: [
      "https://cdn.dummyjson.com/product-images/home-decoration/decoration-swing/1.webp",
      "https://cdn.dummyjson.com/product-images/home-decoration/decoration-swing/2.webp",
      "https://cdn.dummyjson.com/product-images/home-decoration/decoration-swing/3.webp"
    ],
    frames360: [],
    wholesaleTier: { moq: 100, pricePerUnit: 350 },
    retailerTier: { moq: 20, pricePerUnit: 600 },
    consumerTier: { moq: 1, pricePerUnit: 999 },
    nasioUrl: "https://nas.io/acinnovationsandventures/physical-products/decoration-swing-toy-set",
    marketPrice: 500,
    retailStorePrice: 1199,
    inStock: true,
    tags: ["toys", "decoration", "collectible", "kids"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "prod_14",
    name: "Wireless Bluetooth Earbuds Pro",
    slug: "wireless-bluetooth-earbuds-pro",
    category: "Others",
    description: "Premium wireless Bluetooth earbuds with active noise cancellation, 30-hour battery life, IPX5 water resistance, and crystal clear audio. Ideal for music, calls, and workouts.",
    images: [
      "https://cdn.dummyjson.com/product-images/smartphones/iphone-6/1.webp"
    ],
    frames360: [],
    wholesaleTier: { moq: 100, pricePerUnit: 800 },
    retailerTier: { moq: 20, pricePerUnit: 1400 },
    consumerTier: { moq: 1, pricePerUnit: 2499 },
    nasioUrl: "https://nas.io/acinnovationsandventures/physical-products/wireless-bluetooth-earbuds-pro",
    marketPrice: 1200,
    retailStorePrice: 2999,
    inStock: true,
    tags: ["others", "earbuds", "bluetooth", "audio"],
    createdAt: new Date(),
    updatedAt: new Date(),
  }

];

export const CATEGORIES = Array.from(new Set(MOCK_PRODUCTS.map((p) => p.category))).sort();
